name: Java Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Create settings.xml for Maven deployment
    - name: Create settings.xml
      run: |
        mkdir -p ~/.m2
        cat <<EOF > ~/.m2/settings.xml
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ secrets.GITHUB_ACTOR }}</username>
              <password>${{ secrets.GITH_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF

    # Step 5: Build the project with Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 6: Publish to GitHub Packages (if needed)
    - name: Publish to GitHub Packages
      run: mvn deploy -s ~/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}

    # Step 7: Run the tests (the build step will include tests)
    - name: Run Tests with Maven
      run: mvn test -e -X
