name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    # Step 3: Create settings.xml
    - name: Create settings.xml
      run: |
        mkdir -p ~/.m2
        cat <<EOF > ~/.m2/settings.xml
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ secrets.GITHUB_ACTOR }}</username>
              <password>${{ secrets.GITH_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF

    # Step 4: Build with Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 5: Publish to GitHub Packages
    - name: Publish to GitHub Packages
      run: mvn deploy -s ~/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
